# Packs the Blender-rendered icons (tools/blender/icons_out/*.png, see
# tools/blender/icons.py) into one sprite sheet for the game:
#   assets/icons/icons.webp   cells of CELL px, COLS per row, outlined and shadowed
#   src/ui/iconmap.js         name -> cell index, imported by src/ui/gearui.js
#
#   python tools/icons_pack.py        (needs Pillow)

import json, os
from PIL import Image, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "tools", "blender", "icons_out")
OUT_IMG = os.path.join(ROOT, "assets", "icons", "icons.webp")
OUT_MAP = os.path.join(ROOT, "src", "ui", "iconmap.js")
CELL = 112
COLS = 16
OUTLINE = (12, 7, 4)


def finish(im):
    """Dark outline and a soft drop shadow behind the rendered piece, then downscale."""
    im = im.convert("RGBA")
    w, h = im.size
    pad = w // 26
    big = Image.new("RGBA", (w + pad * 2, h + pad * 2), (0, 0, 0, 0))
    big.paste(im, (pad, pad))
    alpha = big.getchannel("A")
    ring = alpha.filter(ImageFilter.MaxFilter(7))
    outline = Image.new("RGBA", big.size, OUTLINE + (0,))
    outline.putalpha(ring.point(lambda a: min(235, a)))
    shadow = Image.new("RGBA", big.size, (0, 0, 0, 0))
    soft = ring.filter(ImageFilter.GaussianBlur(6)).point(lambda a: int(a * 0.55))
    shadow_layer = Image.new("RGBA", big.size, (0, 0, 0, 0))
    shadow_layer.putalpha(soft)
    shadow.paste(shadow_layer, (pad // 3, pad // 2), shadow_layer)
    out = Image.alpha_composite(shadow, outline)
    out = Image.alpha_composite(out, big)
    return out.resize((CELL, CELL), Image.LANCZOS)


def main():
    names = sorted(f[:-4] for f in os.listdir(SRC) if f.endswith(".png"))
    rows = (len(names) + COLS - 1) // COLS
    sheet = Image.new("RGBA", (COLS * CELL, rows * CELL), (0, 0, 0, 0))
    index = {}
    for i, name in enumerate(names):
        cell = finish(Image.open(os.path.join(SRC, name + ".png")))
        sheet.paste(cell, ((i % COLS) * CELL, (i // COLS) * CELL))
        index[name] = i
    os.makedirs(os.path.dirname(OUT_IMG), exist_ok=True)
    sheet.save(OUT_IMG, "WEBP", quality=88, method=6)
    body = json.dumps(index, separators=(",", ":"))
    with open(OUT_MAP, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by tools/icons_pack.py from tools/blender/icons.py renders. Do not edit.\n")
        f.write("// Cell index of each icon in assets/icons/icons.webp (%d px cells, %d per row).\n" % (CELL, COLS))
        f.write("export const ICON_CELL = %d;\nexport const ICON_COLS = %d;\nexport const ICON_ROWS = %d;\n" % (CELL, COLS, rows))
        f.write("export const ICONS = " + body + ";\n")
    print("%d icons, %dx%d, %d KB" % (len(names), sheet.width, sheet.height, os.path.getsize(OUT_IMG) // 1024))


if __name__ == "__main__":
    main()
